#描述：车辆前进方波的周期值，默认：20.0 单位：秒。
Test_MovePeriod: 40.0
#描述：车轮转向的周期值，默认：20.0 单位：秒。
Test_TurnPeriod: 20.0
#描述：车轮最大转角，默认：40.0 单位：度。
Test_TurnAngle: 40.0
#描述：车辆行进最远距离，默认：80.0 单位：米。
Test_StraightLength: 80.0
#描述：测试方波最小值，默认：1.0 单位：米/秒。
Test_SquareMinSpd: 1.0
#描述：测试方波最大值，默认：2.0 单位：米/秒。
Test_SquareMaxSpd: 2.0     
#描述： 测试加速度，默认：0.4m/s2
Test_Acc: 0.3
